tutorials/Assignment4/config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users
  resources :posts do 
    collection { post :import }
  end
  
  get "/login", to: "login#login"
  post "/login", to: "login#setlogin"
  get "/logout", to: "login#setlogout"
  post "/logout", to: "login#setlogout"
end

tutorials/Assignment4/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tutorials/Assignment4/app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send("filter_by_#{key}", value) if value.present?
      end
      results
    end
  end
end

tutorials/Assignment4/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |post|
        csv << post.attributes.values_at(*column_names)
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      posts_hash = row.to_hash
      post = find_or_create_by!(title: posts_hash["title"], description: posts_hash["description"], status: posts_hash["status"])
    end
  end
end

tutorials/Assignment4/app/models/user.rb
class User < ApplicationRecord
  #include Filterable
  def self.search(key, value)
      where("#{key} LIKE ?", "%#{value}%")
  end
end

tutorials/Assignment4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tutorials/Assignment4/app/controllers/login_controller.rb
require './config/initializers/constants.rb'
require './config/initializers/messages.rb'

class LoginController < ApplicationController
  def setlogin
    if EMAIL === params[:email] && PASSWORD === params[:password]
      session[:email] = EMAIL
      redirect_to root_path, notice: SUCCESS
    else
      flash[:alert] = INVALID
      render :login
    end
  end

  def setlogout
    session[:email] = nil
    redirect_to login_path, notice: LOGOUT
  end
end

tutorials/Assignment4/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    @post = Post.new
  end

  def show
    @post = PostService.getPostById(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @is_post_create = PostService.createPost(@post)

    respond_to do |format|
      if @is_post_create
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @post = PostService.getPostById(params[:id])
  end

  def update
    @post = PostService.getPostById(params[:id])
    @is_post_update = PostService.updatePost(@post, post_params)
    if @is_post_update
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = PostService.getPostById(params[:id])
    @is_post_destroy = PostRepository.destroy(@post)

    if @is_post_destroy
      respond_to do |format|
        format.html { redirect_to posts_path }
        format.json { head :no_content }
        format.js { render :layout => false }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :status)
  end
end

tutorials/Assignment4/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sanitize_user_params

  def index
    @users = UserService.getAllUsers
    @users = User.search("name", params[:name]) if params[:name].present?
    @users = User.search("email", params[:email]) if params[:email].present?
    @users = User.search("user_type", params[:user_type]) if params[:user_type].present?
    @users = User.search("address", params[:address]) if params[:address].present?
    @users = User.search("dob", params[:dob]) if params[:dob].present?
    @users = User.search("phone", params[:phone]) if params[:phone].present?
  end

  def show
    @user = UserService.getUserById(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @is_user_create = UserService.createUser(@user)
    if @is_user_create
      flash[:success] = "Created successfully"
      redirect_to @user
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = UserService.getUserById(params[:id])
  end

  def update
    @user = UserService.getUserById(params[:id])
    @is_user_update = UserService.updateUser(@user, user_params)
    if @is_user_update
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = UserService.getUserById(params[:id])
    @is_user_destroy = UserRepository.destroy(@user)

    if @is_user_destroy
      redirect_to root_path, status: :see_other
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :user_type, :dob, :address, :phone)
  end

  def sanitize_user_params
    params[:type] = params[:type].to_i
  end
end

tutorials/Assignment4/app/helpers/application_helper.rb
module ApplicationHelper
end

tutorials/Assignment4/app/helpers/login_helper.rb
module LoginHelper
end

tutorials/Assignment4/app/helpers/posts_helper.rb
module PostsHelper
end

tutorials/Assignment4/app/helpers/users_helper.rb
module UsersHelper
end

tutorials/Assignment4/app/views/login/login.html.erb
<% flash.each do |type, msg| %>
  <% if type == "notice" %>
    <div class="alert alert-success">
      <%= msg %>
    </div>
    <% else %>
    <div class="alert alert-danger">
      <%= msg %>
    </div> 
    <% end %>
<% end %>

<h1>Login</h1>

<%= form_with url: login_path do |form| %>
  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email, class: "form-control", placeholder: "admin@a.com" %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password, class: "form-control", placeholder: "admin" %>
  </div>

  <div>
    <%= form.submit "Login", class: "btn btn-success mt-3" %>
  </div>
<% end %>

tutorials/Assignment4/app/views/posts/_form.html.erb
<%= link_to "Back", posts_path, class: "btn btn-sm btn-primary mt-3" %>
<%= form_with model: @post do |form| %>
  <div>
  <% @post.errors.full_messages_for(:title).each do |message| %>
    <div><%= message %></div>
  <% end %>
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div>
  <% @post.errors.full_messages_for(:description).each do |message| %>
    <div><%= message %></div>
  <% end %>
    <%= form.label :description %><br>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= select(:post, :status, [["public", 0], ["private", 1]], class: 'form-control') %>
  </div>

  <div>
    <%= form.submit :Update, class: "btn btn-sm btn-success mt-3" %>
  </div>
<% end %>

tutorials/Assignment4/app/views/posts/_post.html.erb
  <tr>
    <td><%= link_to post.title, post %></td>
    <td><%= post.description %></td>
    <td><%= post.status == "1" ? "private" : "public" %></td>
    <td>
      <%= link_to "Edit", edit_post_path(post.id), class: "btn btn-sm btn-warning" %>
      <%= link_to "Delete", post_path(post.id), method: :delete, data: { confirm: "Are you sure?" }, :class => "btn btn-sm btn-danger remove_post", :remote => true %>
    </td>
  </tr>

tutorials/Assignment4/app/views/posts/create.js.erb
var posts = document.querySelector("#table");
posts.insertAdjacentHTML("beforeend", "<%= j render(@post) %>");

tutorials/Assignment4/app/views/posts/destroy.js.erb
$('.remove_post').bind('ajax:success', function() {
	$(this).closest('tr').remove();
});

tutorials/Assignment4/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

tutorials/Assignment4/app/views/posts/index.html.erb
<h1>Posts</h1>

<% flash.each do |type, msg| %>
  <div class="alert alert-success">
    <%= msg %>
  </div>
<% end %>
<%= link_to "Back", users_path, class: "btn btn-sm btn-warning" %>
<%= link_to "Create Post", new_post_path, class: "btn btn-sm btn-primary" %>

<%= form_with url: logout_path, html: { class: "form-inline  float-right" } do |form| %>
  <div>
    <%= form.submit "Logout", class: "btn btn-primary" %>
  </div>
<% end %>

<table class="table table-striped mt-3">
  <thead>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Operation</th>
  </thead>
  <tbody id="table">
    <%= render @posts %>
  </tbody>
</table>

<%= form_with(model: @post, id: "new_post", local: false) do |form| %>

    <div class="col">
      <%= form.label :title %><br>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="col">
      <%= form.label :description %><br>
      <%= form.text_field :description, class: "form-control" %>
    </div>

    <div class="col">
      <%= form.label :status %><br>
      <%= form.radio_button :status, 0 %><label for="status_0">Public</label>
      <%= form.radio_button :status, 1 %><label for="status_0">Private</label>
    </div>

  <div>
    <%= form.submit :"Add to form", class: "btn btn-sm btn-primary" %>
  </div>
<% end %>

tutorials/Assignment4/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: @post %>

tutorials/Assignment4/app/views/posts/show.html.erb
<%= link_to "All posts", posts_path, class: "btn btn-sm btn-primary mt-3" %>

<h1>Post Details</h1>
<div class="card">
  <div class="card-body">
    <p>Title: <%= @post.title %></p>
    <p>Description: <%= @post.description %></p>
    <p>Status: <%= @post.status %></p>
  </div>
</div>

tutorials/Assignment4/app/views/users/_form.html.erb
<%= link_to "Back", root_path, class: "btn btn-sm btn-primary mt-3" %>
<%= form_with model: @user do |form| %>
  <div>
  <% @user.errors.full_messages_for(:name).each do |message| %>
    <div><%= message %></div>
  <% end %>
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
  <% @user.errors.full_messages_for(:address).each do |message| %>
    <div><%= message %></div>
  <% end %>
    <%= form.label :address %><br>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div>
  <% @user.errors.full_messages_for(:phone).each do |message| %>
    <div><%= message %></div>
  <% end %>
    <%= form.label :phone %><br>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div>
    <%= form.submit :Update, class: "btn btn-sm btn-success mt-3" %>
  </div>
<% end %>

tutorials/Assignment4/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

tutorials/Assignment4/app/views/users/index.html.erb
<h1>Users</h1>

<% flash.each do |type, msg| %>
  <div class="alert alert-success">
    <%= msg %>
  </div>
<% end %>

<%= link_to "Create", new_user_path, class: "btn btn-sm btn-primary" %>
<%= link_to "See All Posts", posts_path, class: "btn btn-sm btn-warning" %>

<%= form_with url: users_path, method: :get do |form| %>
  <div class="form-row">
    <div class="col">
      <%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="col">
      <%= form.label :address %><br>
      <%= form.text_field :address, class: "form-control" %>
    </div>

    <div class="col">
      <%= form.label :user_type %><br>
      <%= form.radio_button :user_type, 0 %><label for="status_0">Normal User</label>
      <%= form.radio_button :user_type, 1 %><label for="status_0">Super User</label>
    </div>
  </div>

  <div class="form-row">
    <div class="col">
      <%= form.label :email %><br>
      <%= form.text_field :email, class: "form-control" %>
    </div>

    <div class="col">
      <%= form.label :date_of_birth %><br>
      <%= form.date_field :dob, class: "form-control" %>
    </div>

    <div class="col">
      <%= form.label :phone %><br>
      <%= form.text_field :phone, class: "form-control" %>
    </div>
  </div>

  <div>
    <%= form.submit :Search, class: "btn btn-sm btn-primary mt-3" %>
  </div>
<% end %>

<table class="table table-striped mt-3">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>User Type</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Birthday</th>
    <th>Operation</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.user_type == 1 ? "super user" : "normal user" %></td>
    <td><%= user.phone %></td>
    <td><%= user.address %></td>
    <td><%= user.dob %></td>
    <td>
      <%= link_to "View", user_path(user) %>
      <%= link_to "Edit", edit_user_path(user.id), class: "btn btn-sm btn-warning" %>
      <%= link_to "Delete", user_path(user.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
      </td>
  </tr>
  <% end %>
</table>

<%= form_with url: logout_path do |form| %>
  <div>
    <%= form.submit "Logout", class: "btn btn-success mt-3" %>
  </div>
<% end %>

tutorials/Assignment4/app/views/users/new.html.erb
<h1>New User</h1>

<%= render "form", user: @user %>

tutorials/Assignment4/app/views/users/show.html.erb
<%= link_to "All users", root_path, class: "btn btn-sm btn-primary mt-3" %>


<h1>User Details</h1>
<div class="card">
  <div class="card-body">
    <p>Name: <%= @user.name %></p>
    <p>Address: <%= @user.address %></p>
    <p>Phone: <%= @user.phone %></p>
  </div>
</div>